# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPushDockerImage
  displayName: Build and push docker image
  jobs:
  - job: BuildAndPushDockerImage
    displayName: Build and push docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'VM SSH Service'
        runOptions: 'inline'
        inline: |
          docker ps -q --filter "name=backend" | grep -q . && docker stop backend && docker rm -fv backend
          docker pull cyberproton/volunteer-backend:latest
          docker run --name backend -d cyberproton/volunteer-backend
        readyTimeout: '20000'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'cyberproton/volunteer-backend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
        addPipelineData: false
        addBaseImageData: false
      env:
        DOCKER_BUILDKIT: 1
    - task: SSH@0
      inputs:
        sshEndpoint: 'VM SSH Service'
        runOptions: 'inline'
        inline: |
          docker ps -q --filter "name=backend" | grep -q . && docker stop backend && docker rm -fv backend
          docker pull cyberproton/volunteer-backend:latest
          docker run --name backend -d cyberproton/volunteer-backend
        readyTimeout: '20000'
