version: '3.8'

services:
  pgsqldb:
    image: postgres:15.2
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432
